#pragma kernel Multiply

Texture2D tex;
RWStructuredBuffer<uint> result;
int width, height;
SamplerState MyPointRepeatSampler;

[numthreads(32, 32, 1)]
void Multiply(uint3 id : SV_DispatchThreadID)
{
	float4 color = tex.SampleLevel(MyPointRepeatSampler, float2(((width-(float)id.x + 0.5) )/ width, ((height-(float)id.y + 0.5)) / height), 0);
	color *= 255.0;
	result[(id.y * width) + id.x] = ((int)color.r << 16) | ((int)color.g << 8) | ((int) color.b);
}